version: 2
jobs:
  prepare_start:
    docker:
      - image: circleci/node:10.6.0-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}

      - run: yarn start

  test:
    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Execute unit and integration tests
          command: yarn test

  build_deploy:
    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Build App
          command: yarn build

      - run:
          name: Call Netlify Deploy Hook
          command:
            curl -X POST -d ''
            https://api.netlify.com/build_hooks/$NETLIFY_HOOK_ID

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - prepare_start:
          filters:
            branches:
              only: master
      - test:
          requires:
            - prepare_start
          filters:
            branches:
              only: master
      - build_deploy:
          requires:
            - prepare_start
            - test
          filters:
            branches:
              only: master
