version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.6.0-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}

      - run: |
          yarn start
          yarn test

      - run: yarn build

  deploy:
    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - run:
          name: Call Netlify Deploy Hook
          command:
            curl -X POST -d ''
            https://api.netlify.com/build_hooks/$NETLIFY_HOOK_ID

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
